#!/usr/bin/sh

# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message. The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit. The hook is allowed to edit the commit message file.

first_line=`head -n 1 -- $1`
# This strips everything from the right to left
# until if finds a #. So if a line starts with # or
# whitespaces and then #, it will be considered empty.
if [ -z "`echo ${first_line%%#*}`" ]; then
  # Se a mensagem de commit estiver vazia,
  # simplesmente retorna e deixa o git
  # fazer o que normalmente faria.
  exit 0
fi

# A mensagem deve começar com uma tag, tipo assim: [uma tag]
# A mensagem pode ser apenas uma tag e mais nada ou uma tag e um título.
# Caso haja título, deve haver espaço entre o fim da tag e o começo do título.
if echo $first_line | grep -vq "^\[.\+\]\($\| .\+\)"; then
  # https://stackoverflow.com/questions/3417896/how-do-i-prompt-the-user-from-within-a-commit-msg-hook
  # https://victoria.dev/blog/an-automatic-interactive-pre-commit-checklist-in-the-style-of-infomercials/
  # Read user input, assign stdin to keyboard
  exec < /dev/tty

  printf 'A mensagem de commit está sem uma tag no começo ou mal formatada (sem espaço após a tag). Ex: [tag] Mensagem\n'

  # Also transform files inside ARCHIVE to their first names, ex ARCHIVE/i3 becomes i3.
  staged_files=`git diff --name-only --staged | sed 's/\(ARCHIVE\|EXAMPLE-FILES\)\/\(.*\)/\2/' | cut -d '/' -f 1 | sort -u`

  # Translate nvim to neovim and awesome to awesomewm because reasons?
  # I've always done it this way, so I want to mantain it.
  staged_files=`echo $staged_files | sed 's|nvim|neovim|'`
  staged_files=`echo $staged_files | sed 's|awesome|awesomewm|'`

  # Join the files with a /
  tag="[`echo $staged_files | sort -u | tr ' ' ','`]"

  printf "Adicionar automaticamente $tag?\n"
  printf "[Y/n/(i)gnorar] "
  read resposta

  case $resposta in
    ''|[yYsS])
      echo "$tag `cat $1`" > $1
      ;;
    [iI])
      exit 0
      ;;
    *) exit 1
      ;;
  esac
fi
