#!/bin/sh

alias als='nvim ~/.aliases'

alias ls='ls --color=auto -F --group-directories-first'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ll='ls -l'
alias la='ls -A'
alias lla='ls -lA'
alias lal='ls -Al'

# Meus apelidos
alias showppa='echo "/etc/apt/sources.list.d" && ls /etc/apt/sources.list.d'
alias diff='diff --color=auto'
alias path='echo $PATH | tr ":" "\n"'
alias glo='git log --oneline'
alias gl='sh ~/scripts/git-stuff/git-log-main-master.sh --oneline'
alias gds='git diff --staged'
alias gd='git diff'
alias gs='git status'
alias gk='git checkout'
alias gb='git branch'
alias simplexev='sh ~/scripts/simplexev.sh'
alias pwdcp="pwd | tr -d '\n' | xclip -selection clipboard && pwd"
alias normalizechmod='sh ~/scripts/chmod-back-to-normal.sh'
alias browsersync='browser-sync start --server --directory --files **/*'
alias vimtime='nvim --startuptime nvim_startuptime.log'
alias vimrc='nvim ~/.config/nvim/lua/plugins.lua ~/.config/nvim/lua/init.lua ~/.config/nvim/lua/settings.lua ~/.config/nvim/init.vim'
alias bashrc='nvim ~/.bashrc ~/.bash_profile'
alias tmuxrc='nvim ~/.tmux.conf'
alias awerc='nvim ~/.config/awesome/rc.lua'
alias alrc='nvim ~/.config/alacritty/alacritty.yml'
alias i3rc='nvim ~/.config/i3/config ~/.config/i3/i3blocks.conf'
alias polrc='nvim ~/.config/polybar/config'
alias zshrc='nvim $ZDOTDIR/.zshrc ~/.zshenv'
alias notouchpad='xinput disable Elan\ Touchpad'
alias vimgit='git diff --name-only | sort -u | xargs nvim'
alias tmuxls='sh ~/scripts/parse-tmux-ls.sh'
alias rubomaster='sh ~/scripts/git-stuff/get-files-rubocop.sh'
alias rspecmaster='sh ~/scripts/git-stuff/get-files-rspec.sh'
alias readme='ls | grep -i readme | xargs glow -p'

[ -f "$HOME/.local/.my_aliases" ] && source "$HOME/.local/.my_aliases"
