# https://toml.io/en/v1.0.0
# https://alacritty.org/config-alacritty.html

# Color scheme
general.import = ['~/.config/alacritty/modified-catppuccin-frappe.toml']

[env]
TERM = 'xterm-256color'

[window]
decorations = 'none'
opacity = 0.9
dynamic_title = true

[window.padding]
x = 4
y = 0

[scrolling]
history = 10000

[font]
size = 9.5

[cursor]
unfocused_hollow = true
blink_interval = 500

[cursor.style]
blinking = 'On'

[hints]
alphabet = 'asdfhjklgçqweryuiotpzxcvbnm,1234567890;.'

[[hints.enabled]]
action = 'Paste'
post_processing = true
binding = { key = 'H', mods = 'Control|Shift' }
# regex = '([0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}|[a-f0-9]{40})|([a-f0-9]{12})|([a-f0-9]{7})'
# Se cortar, tentar descomentar o de baixo e comentar o de cima
regex = '([0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12})|([a-f0-9]{7,})'

# https://alacritty.org/config-alacritty.html
[[hints.enabled]]
command = 'xdg-open'
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = 'U', mods = 'Control|Shift' }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[keyboard.bindings]]
action = 'ScrollHalfPageDown'
key = 'J'
mods = 'Shift|Control'

[[keyboard.bindings]]
action = 'ScrollHalfPageUp'
key = 'K'
mods = 'Shift|Control'
