#!/bin/sh

# This file is called as a shell script like this:
# xplugrc TYPE DEVICE STATUS ["Optional Description"]
#          |    |      |
#          |    |       `---- connected or disconnected
#          |     `----------- HDMI3, LVDS1, VGA1, etc.
#           `---------------- keyboard, pointer, display

# Examples:
# xplugrc display HDMI3 disconnected
# xplugrc keyboard 3 connected "Topre Corporation Realforce 87"

# Será que tem como fazer algo parecido pra headfones com acpi_listen?

if [ "$1" = display ]; then
  if [ "$3" = disconnected ]; then
    "$HOME/scripts/monitores.sh" single
    exit
  fi

  if [ "$2" = 'HDMI-1' ]; then
    "$HOME/scripts/monitores.sh" right
    exit
  fi
fi

if [ "$1" = keyboard ]; then
  if [ "$3" = connected ]; then
    xset r rate 220 25
    xmodmap "$HOME/.Xmodmap"
    exit
  fi
fi
