# vim: ft=sh

# https://zsh.sourceforge.io/Intro/intro_3.html
# https://www.reddit.com/r/zsh/comments/3ubrdr/proper_way_to_set_zdotdir/
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

# LOG=$HOME/zshenv-invocations
# echo "=== $(date) ===" >>$LOG
# echo "Caller: $0" >>$LOG

export ASDF_CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/asdf/asdfrc"

# The format of process time reports with the time keyword.
# The default is ‘%J %U user %S system %P cpu %*E total’.
# https://zsh.sourceforge.io/Doc/Release/Parameters.html
export TIMEFMT=$'\nuser\t%*Us\nsystem\t%*Ss\ntotal\t%*Es'

[ -f "$ZDOTDIR/zshenv.local" ] && . "$ZDOTDIR/zshenv.local"
