# vim: ft=sh

# https://zsh.sourceforge.io/Intro/intro_3.html
# https://www.reddit.com/r/zsh/comments/3ubrdr/proper_way_to_set_zdotdir/
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

# LOG=$HOME/zshenv-invocations
# echo "=== $(date) ===" >>$LOG
# echo "Caller: $0" >>$LOG

[ -f "$ZDOTDIR/zshenv.local" ] && . "$ZDOTDIR/zshenv.local"
