source "$HOME/.asdf/asdf.sh"
fpath=(${ASDF_DIR}/completions $ZDOTDIR/completions $fpath)

autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

# Include hidden files
_comp_options+=(globdots)

setopt hist_ignore_all_dups inc_append_history
HISTFILE=~/.cache/zsh/history
HISTSIZE=4000
SAVEHIST=4000

# Lines configured by zsh-newuser-install
setopt nomatch notify
unsetopt autocd beep extendedglob
# End of lines configured by zsh-newuser-install

bindkey -e

git_color() {
  local git_status="$(git status 2> /dev/null)"
  local output_styles=""

  # if [[ $git_status =~ "rebas" ]]; then
  #   output_styles="\e[1;35m"
  #   # Não funciona :shrug:
  if [[ $git_status =~ "nothing to commit, working tree clean" ]]; then
    output_styles="9"
    # vermelho
  elif [[ $git_status =~ "nothing added to commit but untracked files present" ]]; then
    output_styles="11"
    # amarelo
  elif [[ $git_status =~ "no changes added to commit" ]]; then
    output_styles="11"
    # amarelo
  elif [[ $git_status =~ "Changes to be committed" ]]; then
    output_styles="14"
    # azul claro
  else
    output_styles="white"
  fi

  echo "$output_styles"
}

autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '(%b)'
setopt PROMPT_SUBST

# Cores escuras / claras
# vermelho | verde | amarelo | azul | magenta | ciano | branco | preto/cinza
#   1/9    |  2/10 |   3/11  | 4/12 |   5/13  |  6/14 |  7/15  |     8/16
# https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html#Prompt-Expansion
PROMPT='%B%F{green}%n@%m%F{white}:%F{blue}%~
%B%F{$(git_color)}${vcs_info_msg_0_}%0(?..%F{magenta}[%?])%f%bλ '
RPROMPT='%B%F{6}{zsh}%f%b'

source "$HOME/.aliases"

bindkey "^F" clear-screen
bindkey "^T" kill-line

# OBS: Enter produz "^M"
# https://zsh.sourceforge.io/Doc/Release/Zsh-Modules.html#Menu-selection
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect '^M' accept-search
bindkey -M menuselect 'u' undo

# https://stackoverflow.com/questions/37772712/zsh-how-to-make-tab-completion-need-no-space-to-next-word-after-cursor
bindkey "^I" expand-or-complete-prefix

# Control + esquerda/direita, respectivamente
bindkey ";5D" backward-word
bindkey ";5C" forward-word

source "$ZDOTDIR/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"

# Será que isso devia ficar aqui?
# Aumenta a quantidade de vezes que uma tecla é apertada quando seguramos ela
xset r rate 220 25

eval "$(zoxide init zsh)"

sh "$HOME/scripts/lambda-fetch.sh"

#https://www.tecmint.com/tips-for-tmux-terminal-sessions/
if tmux ls 1>/dev/null 2>&1 && [ -z "$TMUX" ]; then
  printf "Já existe pelo menos uma instância do \e[32mtmux\e[0m rodando:\n"
  /bin/sh ~/scripts/parse-tmux-ls.sh
else
  # ORIGINAL_TERMINAL_EMULATOR
  if [ "$(ps -o 'cmd=' -p $(ps -o 'ppid=' -p $$))" = alacritty ]; then
    # tmux attach -t default || tmux new -s default
    /usr/bin/tmux
  fi
fi
