return function()
  local current_mode = vim.api.nvim_get_mode().mode
  local t = {
    ['n'] = 'NORMAL',
    ['no'] = 'O-PENDING',
    ['nov'] = 'O-PENDING',
    ['noV'] = 'O-PENDING',
    ['no\22'] = 'O-PENDING',
    ['niI'] = 'NORMAL',
    ['niR'] = 'NORMAL',
    ['niV'] = 'NORMAL',
    ['nt'] = 'NORMAL',
    ['ntT'] = 'NORMAL',
    ['v'] = 'VISUAL',
    ['vs'] = 'VISUAL',
    ['V'] = 'V-LINE',
    ['Vs'] = 'V-LINE',
    ['\22'] = 'V-BLCK',
    ['\22s'] = 'V-BLCK',
    ['s'] = 'SELECT',
    ['S'] = 'S-LINE',
    ['\19'] = 'S-BLCK',
    ['i'] = 'INSERT',
    ['ic'] = 'INSERT',
    ['ix'] = 'INSERT',
    ['R'] = 'REPLCE',
    ['Rc'] = 'REPLCE',
    ['Rx'] = 'REPLCE',
    ['Rv'] = 'V-REPLCE',
    ['Rvc'] = 'V-REPLCE',
    ['Rvx'] = 'V-REPLCE',
    ['c'] = 'COMMND',
    ['cv'] = 'EX',
    ['ce'] = 'EX',
    ['r'] = 'REPLCE',
    ['rm'] = 'MORE',
    ['r?'] = 'CONFIRM',
    ['!'] = 'SHELL',
    ['t'] = 'TERMINAL',
  }

  return t[current_mode] or current_mode
end
